name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - aiohttp
      - polars
      - ipykernel
      - jupytext
      - ruff-lsp
      - ruff
      - black
      - python-dotenv
      - orjson
      - aiohttp_socks
